### ISSUE TITLE
DateTimePicker: Manual editing and click resets the input

### ISSUE THREAD

**Issue by andersem** [jquense/react-widgets#102]
Using the DateTimePicker v2.6.0, when:

1. The input is populated
1. I manually edit by typing, for example from "1. februar 2015 01:00" to "2. februar 2015 01:02". (Norwegian culture)
1. I click in the input field, the selected date goes back to "1. februar 2015 01:00"

It works as expected if I edit manually, and then click another place, just not in the same input.

**Comment by jquense** [comment]
Hi there,

 I am trying to reproduce the issue on the docs site but not able to. Typing and clicking seems to work fine trying your steps or anything else I can think of.

**Comment by andersem** [comment]
The issue isn't there in your examples, so it might just the combination of value, onChange and setState that I'm using.

When looking for the bug in the examples, I came over another one:

Go to the onChange-example, manually edit the date, for example I changed 05 to 06. Click in the input under, which results in the top input being cleared.

**Comment by jefferydutra** [comment]
I am also experiencing this issue, I can not change date/times by typing.  I have to open the calendar to change values

**Comment by jquense** [comment]
@jefferydutra can you reproduce this behavior on the doc site? If values are being "cleared" out when typing its because the typed value is failing to parse to a date object and so becomes `null`

It sounds tho like you are running into a different issue? I can't think of reason why the value would not trigger an onChange, what browser are you using, can you try another to see if it continues?

**Comment by jefferydutra** [comment]
It was not a bug, it was a mistake in my moment abstraction in front of the DateTimePicker.  Sorry for the delay.

**Comment by jquense** [comment]
glad to hear it wasn't a bug :)
