### ISSUE TITLE
Unable to create keydown event that simulates onSelect - ComboBox

### ISSUE THREAD

**Issue by rralbritton** [jquense/react-widgets#1027]
I am using react widget combobox in a form. When a user click on a suggested value or presses enter on that value, the valueField attribute gets populated. I want to replicate this behavior when a user clicks tab over a value but I can not seem to get a onKeyDown event to work. I can get it to recognize the onKeyDown event, but have been unable to grab the object that the user has selected by tabbing over. I can get the value in TextField, but I'm looking to get the entire object that the valueField provides with the onSelect prop. 

```

 handleOnSelect = value => {
        this.setState(() => ({ user: value }))
        this.props.change('firstName', value.firstName);
        this.props.change('lastName', value.lastName);
        this.props.change('email', value.email);
    }

 handleKeyDown = (e, valueField) => {

        if (e.keyCode === 9) {
            //need to simulate a e.keyCode === 13 here;
            console.log(valueField); //comes up as undefined
        }
    }
                           <Combobox
                                name="user"
                                placeholder="Search by First Name..."
                                data={dtsStaff}                            
                                suggest={true}
                                value={fullName}
                                valueField="fullName"
                                textField="fullName"
                                filter="startsWith"
                                onChange={fullName => this.setState({ fullName })}
                                onSelect={valueField => this.handleOnSelect(valueField)}
                                onKeyDown={(e, valueField) => this.handleKeyDown(e, valueField)}
                            />
```

  [1]: http://jquense.github.io/react-widgets/api/Combobox/

**Comment by olmobrutall** [comment]
Hallo @jquense, what is the solution for this problem? 

I'm also missing a `autoSelectOnTab` option, or `autoSelectOnFocus`, this is the default behaviour on a native HTML select: 

### In html `<select/>`
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
* If you are focused on the select and press `[o]` and then `[Tab]`, `Opel` is selected. 

### In react-widgets `DropdownList`
https://jquense.github.io/react-widgets/docs/DropdownList
* If you are focused on the select and press `[y]` and then `[Tab]`, nothing happens. 
* If you are focused on the select and press `[y]` , `[Down]` and then `[Tab]`, nothing happens. 
* If you are focused on the select and press `[y]` , `[Down]`, `[Enter]`  then it works, and then you have to press `[Tab]` to move to next control. 

### In react-widgets `Combobox`
https://jquense.github.io/react-widgets/docs/DropdownList
* If you are focused on the select and press `[y]` and then `[Tab]`, nothing happens <-- Probably this is OK like this, because is a free text input. 
* If you are focused on the select and press `[y]` , `[Down]` and then `[Tab]`, nothing happens. 
* If you are focused on the select and press `[y]` , `[Down]`, `[Enter]`  then it works, and then you have to press `[Tab]` to move to next control. 

I could do a PR if this options will be welcomed.

**Comment by jquense** [comment]
I'm not sure what the question is @olmobrutall `select` behavior tends to differ between platforms and browsers, we aren't necessarily trying to match every UX thing they do (some of which i think are actively bad). Around selection behavior in particular RW, doesn't "auto select" things via the keyboard, you need to it "enter" to select, this is comparable to pointer behavior where you hover over an option and click to select. I find this UX is often preferable as it allows users to explore options with the keyboard without changing it, e.g. they can tab out without selecting anything new and leave the existing value alone

**Comment by olmobrutall** [comment]
I've checked using Chrome in the Mac from my wife and you're right, the behaviour is OS dependant (of course on mobile phones is very different).

Still, the type of applications that I do are typically used from Windows computers, so the current behaviour is inconsistent with this environment. 

Moreover, they are typically data-intensive applications and the feedback that I become when using RW is that pressing 3 keys to confirm selecting a value (Down, Enter, Tab) instead of one (Tab) is suboptimal.

I'm not asking to change the default behaviour, just to make a PR to add a new additional option.
