### ISSUE TITLE
Custom ItemComponents cannot use valueField & textField

### ISSUE THREAD

**Issue by nickknw** [jquense/react-widgets#109]
First, thanks for the great work on this, especially the options provided for custom rendering etc. Very nice! That said I do have one issue:

When I provide a custom ItemComponent to a DropdownList, I cannot take advantage of any configured valueField or textField properties to render the list items correctly.

This is a problem in my situation because my custom ItemComponent needs to be able to be used without knowing the structure of the data in advance (otherwise I would just pull out the text field property directly like in the example).

If List.jsx passed along the valueField and textField properties to its ItemComponent then my custom item component could use DataHelpersMixin to render the correct values. IMO this scenario would make for a useful example for the documentation as well :)

**Comment by jquense** [comment]
Hey there thansk for the issue,

The assumption is that if you are adding an ItemComponent you also know the structure of the data, which i imagine is generally the case. Plus if you are just going to render the text why use a component anyway :P? Could you talk a bit more about your use case where you wouldn't know? Are you building a more general template? Setting a default?

In general I don't think its a bad idea but I think instead of passing the text/value fields which themselves require non public code to evaluate correctly (`DataHelpersMixin`) they aren't much help. The better option seems to me to just pass in the evaluated values i.e. the text string and the value object. Would that solve your use case or do you specifically need the fields/accessors?

**Comment by nickknw** [comment]
Sure yeah, so my use case is that I want some dropdowns to have a nice way to clear the currently selected value. Inserting a blank item at the top of the list works well but we wanted to make it more obvious to the user what was happening. So I wrote a small custom ItemComponent for our dropdowns that just does this:

```javascript
       // turn blank entry into a Clear Value list item
        if (_.isUndefined(item) || _.isNull(item) || _.isEmpty(item)) {
            item = "Clear Value";
            props.className = 'clear-value-option';
        }

        return (<span {...props}>{item}</span>);
```

It is more of a general functionality change that should apply across all our dropdowns (or just the ones that need blank values, anyway).

>  The better option seems to me to just pass in the evaluated values i.e. the text string and the value object. Would that solve your use case or do you specifically need the fields/accessors?

Yep, that would solve it, and that does seem like a better option! I don't need the fields specifically, just want to be able to conditionally render different text based on what would have been rendered.

**Comment by nickknw** [comment]
That's great, thanks!
