### ISSUE TITLE
Is it possible to make read-only still selectable for a Combobox?

### ISSUE THREAD

**Issue by fourq** [jquense/react-widgets#110]
Is it possible to make read-only still selectable? At the moment read-only disables the dropdown of a combobox.

**Comment by jquense** [comment]
hey!

Not quite sure I get the question, You looking to be able to select from the dropdown but not type in the input? If that's the case, yeah you can't do that with a combobox (or any dropdown) if they are `readOnly` since they try and follow the general guidelines for `readOnly` behavior of inputs. 

You might be able to get most of the way there though by using `onSelect` as your `onChange` since it only fires when an item is selected from the list. if you are controlling the value prop that would essentially make typing a noop.

Alternatively if you don't want to allow typing I might recommend just using the the `DropdownList` :)

**Comment by fourq** [comment]
My validation is catching any values not in the list so I should be good to go. I didn't realize that, that was a difference in the DDL and CB. Thanks as always, and hey! a reminder.... PM me the donate link. =)
