### ISSUE TITLE
HTML5 Input Validations

### ISSUE THREAD

**Issue by frostme** [jquense/react-widgets#120]
It would be nice for input validations on widgets, and the ability to provide the display message.

## Validations
- required attribute
- size attribute
- max-length
- min-length
- input types
- pattern

**Comment by jquense** [comment]
validation and error messages are beyond the scope of this library BUT I also have a form library that has a built-in integration with react-widgets. you can check it out at. http://jquense.github.io/react-formal/docs/#/

I am reticent in general to make them work with the built in html5 validations because it involves a lot of hacky hidden inputs and other cruft to get the browsers to play nicely with them all, but I'm open to it if you have any ideas about how to do it.
