### ISSUE TITLE
"Uncaught TypeError: type.toUpperCase is not a function" when bundling with Webpack

### ISSUE THREAD

**Issue by cosminnicula** [jquense/react-widgets#131]
I've created a custom DropdownList called `MyDropdownList` here https://github.com/cosminnicula/ddlwebpack and bundled it with Webpack.

The bundle is consumed in a client project here https://github.com/cosminnicula/ddlwebpackclient. When I browse index.html and click on the DropdownList, I get the following error: "Uncaught TypeError: type.toUpperCase is not a function".

I'm using react-widgets 2.6.2

Any idea on this error?

**Comment by cosminnicula** [comment]
This is caused by the fact that `react-widgets` does not export the 'List' component inside https://github.com/jquense/react-widgets/blob/master/src/index.js
I need to extend the `List` component in order to implement "disabled items" functionality.

Would you take a PR for this?

**Comment by jquense** [comment]
No need to have List be in the main export, just require it directly from the lib folder if you are using webpack: `require('react-widgets/lib/List')`

**Comment by cosminnicula** [comment]
Thanks

**Comment by cosminnicula** [comment]
Just a question here: is there a way to specify the List as "external" when building with Webpack? I want my wrapper to be as light as possible.

**Comment by jquense** [comment]
In general your bundle will be as small as possible when you don't use externals, and just require() what you need, that way webpack will only include the needed pieces instead of the entire thing.

if you are having problems in your modules that use react-widgets including it more then once, consider making react-widgets a peerDependency of those modules instead of a direct one.

**Comment by cosminnicula** [comment]
Let's take for example https://github.com/cosminnicula/ddlwebpack/blob/master/src/MyDropdownList/my-list.jsx

- require('react-widgets') ->  configured as `external` with Webpack
- require('react-widgets/lib/List') and require('react-widgets/lib/util/propTypes') -> these will inflate the bundle, since they cannot be specified as `external` with Webpack

As I will require more `/lib` resources, the bundle of the library will increase in size. It would have been nice if I could have mark the `/lib` as external with Webpack, just like with `React` or `react-widgets` and force the client of the library to require `React`, `react-widgets`, `/lib` before actually using it. Don't know if I explained it well enough.

Regarding the peer dependencies, do you have an example?

**Comment by jquense** [comment]
> require('react-widgets') -> configured as external with Webpack

yes you fix this by not doing that. There is no reason to mark it as external just require it and let webpack bundle it. then it will all work fine. IF you want react-widgets in a different bundle, use code splitting, which you can learn about on the webpack website.

**Comment by cosminnicula** [comment]
I want react-widgets to be marked as external for the same reasons I want React to be marked as external: forces you to only have one version of a library in a project.

I'm not referring to code splitting here (e.g. Webpack vendors plugin).

**Comment by jquense** [comment]
if you only have one copy of it in your projectm then you only have one copy there is no need to mark it external, I don't ever mark react as external and it's never caused any issues. there is only one copy of react bundled because all react packages mark it as a peerDependency.

You may have some misunderstandings about how webpack bundles, I would suggest checking out their gitter room and asking your questions there, they are usually very helpful, and will be more knowledgable than me about using webpack, and your question is more about using webpack to manage dependencies then it is about react-widgets.
