### ISSUE TITLE
DropdownList - disabled items

### ISSUE THREAD

**Issue by cosminnicula** [jquense/react-widgets#133]
This is related with #83

The enhanced DropdownList that should support disabled items is here https://github.com/cosminnicula/ddlwebpack

The client that consumes this component is here https://github.com/cosminnicula/ddlwebpackclient

However, browsing index.html gives me two errors:
- `Uncaught TypeError: Cannot read property 'toUpperCase' of undefined`
- `Uncaught Error: Invariant Violation: findComponentRoot(..., .0.1.2.0.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ```

I have followed your suggestion from #131, but the problem persists :(

**Comment by jquense** [comment]
You have a problem somewhere in your build and bundling step I would think or you aren't exporting something.. I'm sorry but I can't provide support for your components, as I didn't build them. The issue you are having is not due to the problem in #83, as I see you fixed that. As much as I would love to help I do not have a lot of time to sift through your projects to find bugs, sorry.

**Comment by cosminnicula** [comment]
I figured out what I was missing when extending the `List`. I just had to add the following lines of code, although I don't quite understand why this is needed:
```
CustomPropTypes = require('react-widgets/lib/util/propTypes');
...
propTypes: {
    ...
    itemComponent: CustomPropTypes.elementType
    ...
}
...
```

This is related with #83, as there is just a gist and one might want to see the DropdownList "disabled items example" in action in the browser. Hope that this will help others too.
