### ISSUE TITLE
Update remaining dependencies (not dev)

### ISSUE THREAD

**Issue by AlexKVal** [jquense/react-widgets#151]
- [x] - classnames
- [x] - globalize - won't be updated till next breaking release.
- [ ] - react-bootstrap

There are three more dependencies left to update.
```sh
$ npm up
$ npm outdated
```
![screen shot 2015-07-02 at 11 21 34 am](https://cloud.githubusercontent.com/assets/847572/8472838/3ffc984e-20ad-11e5-8437-94e9c7464d46.png)

The two of them
https://www.npmjs.com/package/globalize and
https://www.npmjs.com/package/classnames
are in npm: `dependencies` section.
Therefore it needs a diligent consideration about their versions bumping.

`classnames` updates straightforward. (the next PR)
But others two need more attention.

**Comment by jquense** [comment]
globalize can't be updated 1.0.0 has a ton of very breaking changes and doesn't work with webpack, which is why it's pinned to the version it's at for now. someday I will upgrade but it will be on a major version bump as it will be a breaking change. 

Also what is the breaking change in classnames? generally I don't have much of a reason to upgrade the normal deps when the all work fine, since it can introduce bugs accidentally.

**Comment by AlexKVal** [comment]
> generally I don't have much of a reason to upgrade the normal deps when the all work fine, since it can introduce bugs accidentally.

That is the cause why I was asking about what is the best (for you) policy to update
normal deps :wink:  Thank you for the clarification.
( nevertheless you've merged classnames update though you could just say no to it :angel: )

**Comment by jquense** [comment]
It's mostly that there isn't a strong incentive too when they work fine :) I appreciate it tho. I do forget about them, classnames was a good example, no reason not to update it

**Comment by jquense** [comment]
I think i am going to stick with the old RB for now since i don't have any strong incentive to update it right now.
