### ISSUE TITLE
When message is shown, it's not dismissed by clicking on the input blank area

### ISSUE THREAD

**Issue by yzhanginwa** [jquense/react-widgets#154]
When message is shown, it's not dismissed by clicking on the input blank area. This is against intuition.

**Comment by jquense** [comment]
Hi there, that's for the issue. can you explain a bit more what you mean. what message? and what widget are you talking about.

**Comment by yzhanginwa** [comment]
"The filter returned no result". It could be dismissed by pressing "esc" or "alt + up arrow". But for normal users, they don't have these knowledge. It may help a lot if the message could be dismissed by clicking the blank input area.

**Comment by jquense** [comment]
thanks for the follow-up. I assume you mean for the multiselect? esc to close popup is pretty standard (see the native select tag). you can also tab or remove focus to close it. since the multiselect select doesn't make much sense with the popup closed, I think the current behavior is probably the best.

**Comment by yzhanginwa** [comment]
Yes, it is multiselect. Esc is standard but not convenient/intuitive for non-tech users (imho). Tabbing or removing focus seems not working for me. In my case, I had buttons under the input. The open popup blocked the buttons. I had to close the popup before clicking on the buttons(to submit value or cancel it). So for me, it would be great if we have the feature of toggling the popup by clicking the blank area (next to and including the input cursor ) in the input box.

**Comment by jquense** [comment]
I don't want to toggle the dropdown in this case because it just presents the user with an empty text input which gives no indication to the inputs use, which in my opinion is a worse situation. especially there is no value in closing the popup while the user is still interacting with it. 

If tabbing or clicking off the select is not closing it you might have a different issue...overall I am going to keep the current behavior as the default but you can fairly easily implement the behavior yourself by wrapping the select in your own component and using the onClick, open, and onToggle props :)
