### ISSUE TITLE
Search Bar Component

### ISSUE THREAD

**Issue by ksespinola** [jquense/react-widgets#168]
I'd like to start on a Search Bar component for the library, similar to the functionality of `DropdownList` with a filter.

Is this in alignment with vision for the library, and/or does someone have an implementation already?

**Comment by jquense** [comment]
maybe talk a little bit more about what you are trying to accomplish? Like a typeahead/autocomplete component?  What would it do that was different then the current widgetsm etc?

I am definitely open to the idea, but it'd be a good idea to think it through a bit in words before ya jump in.

**Comment by ksespinola** [comment]
Ideally I'd like to put together something like this: https://twitter.github.io/typeahead.js/.

I was thinking of starting by simply filtering data for the dropdown based on the string entered in the searchbox.

Phase 1: Filter dropdown results based on string entered in the input.
Phase 2: pass a `endpoint` prop instead of the `data` Array.
Phase 3: autocomplete, typehead?

**Comment by jquense** [comment]
sounds great, here are a few thoughts and some general guidelines i follow when adding a new widget.

__thoughts__
- I wouldn't add the xhr stuff to the widget itself, I would continue to use the `value`, `data`, `onChange` on change interface. It keeps the components flexible, declarative, and allows for server rendering. Users can fairly easily create wrapper components that fetch data if needed. You want to couple the data getting/searching logic as little as possible.
- you can check out the layout and filtering logic in the Multiselect for inspiration

__general guidelines__
- all widgets need to use the correct html `role`s and ARIA so that screen readers can understand them
- anything that can be down with a mouse, must be possible with _just_ a keyboard
- should work with right-to-left languages and cultures (see the rtl mixin)
- follow the same basic styling as the others
