### ISSUE TITLE
When using DateTimePicker with calendar=false, manually entered time resets date to 1/1

### ISSUE THREAD

**Issue by jedlinlau** [jquense/react-widgets#172]
I'm using the DateTimePicker with calendar=false, like so:
```JavaScript
             <DateTimePicker
                calendar={false}
                value={timeRangeStart}
                onChange={this.configChange.bind(this, "timeRangeStart")}
              />
```

When I pick a time from the dropdown, the date returned in the value is set to the current date. For instance, selecting "9:00 AM" in the dropdown returns this value:
```
configChange: value=Mon Jul 27 2015 09:00:00 GMT-0700 (PDT)
```

However, when I manually enter a time (i.e., type in "9:00 AM" in the text field), the date returned in the value is set to January 1:
```
configChange: value=Thu Jan 01 2015 09:00:00 GMT-0800 (PST)
```

This would normally not be an issue, since I'm only concerned with the time of day (calendar=false). However, setting the date to 1/1 changes the GMT offset (GMT-0700 if it's today, GMT-0800 if it's 1/1), which impacts the time.

**Comment by jquense** [comment]
hmm interesting, thanks for the bug report, I will take a look.

**Comment by jquense** [comment]
OK I've taken a look, and unfortunately there isn't much I can do to fix it :/. Globalize decided to  the month and day on time only formats to jan 1st. I can't actually adjust for it because I have no idea whether the date format being used is a "time only" format since globalize doesn't expose that sort of metadata. However, if you do know that the format is time only then you can fix it in the `onChange` handler by changing the month, and day to the current one, that will fix the offset.

**Comment by jedlinlau** [comment]
Thanks for looking into it. Yes, that workaround is what I'm doing now.
