### ISSUE TITLE
DateTimePicker's onChange not triggered when pressing enter

### ISSUE THREAD

**Issue by andersem** [jquense/react-widgets#203]
See example at https://github.com/andersem/reactwidgetsbug

When pressing enter directly after manually editing a DateTimePicker, the onChange-function isn't called. If, however, you press outside the box, it works.

My users expect to be able to submit using the enter button without further ado.

**Comment by jquense** [comment]
Hi there, 

there are a few issues with that. "Enter" is the default submit form hotkey in browsers, when the cursor is judt sitting in an input. If I used it would conflict with that, and cause inexplicable behavior when used in a `<form/>`. If a user shouldn't have to think about this at all, as far as they are concerned, the value is set as they type, there is no sense in which they should need to "commit" the change by hitting a key, in the same way typeing in a textbox doesn't require hitting the enter key to set the value.

**Comment by VanCoding** [comment]
I also think this is an issue.
When one presses enter and the picker-dialog is open, then it also fires the onChange event.
I think the same should happen when one types in his own option and then wants to select that.

When I tested it within the form tag, the onChange event was not even fired after the onSubmit event of the form. I don't use "from" tags, but if it really leads to issues with it, then we could at least add in as an option.

**Comment by jquense** [comment]
this is not possible or intuitive "enter" does not function like that for an form inputs, so it doesn't make sense here. `onChange` is fired when the input blurs, which is exactly how native inputs work.

**Comment by VanCoding** [comment]
Ok, it doesn't seem like you are interested in other use cases than the usage in forms.
That's fine, I'll make a fork then :)

Thank you for those awesome widgets btw! :+1:

**Comment by corbmanj** [comment]
This issue is annoying for keyboard-only users. I agree that the enter button does by default submit the form, but that functionality doesn't make sense when there is no form to submit. Currently the enter button causes the page to refresh with a URL parameter when used in a single-page app. It would be very nice to have the option for a preventDefault() here

**Comment by jquense** [comment]
the behavior is all the browsers. you can listen for keydown and prevent it if you want. The point is hit enter to confirm a value in an input is not how html inputs of any kind work. You are free to disagree with that behavior but you'd have to take it up with browser vendors.

**Comment by VanCoding** [comment]
@jquense Well, imagine for a second that the text-box of the date-picker is a searchbox. And while you're typing in a date you get an invisible drop-down list of suggested dates that would match your search. And by pressing enter, you select the first of those dates and replace the input's contents with the date string. Does it start to make sense now?

This is how any searchbox works, be it react-select or even chromes omnibar.

For me, a datepicker is nothing else than a searchbox for dates, and the calendar is its dropdown list of dates. That's why I expect it to behave like requested. But I don't know if I'm alone with this :P

**Comment by jquense** [comment]
the major difference is that there is no dropdown. when there is enter works. in this case there isn't. again this is exactly how normal html inputs work.  a normal html textbook does not fire a change event until you blur out of it, and hitting enter would submit the form. 

again,  you are free to implement your own bespoke behavior if you want. but as a library we should follow the well established conventions for the platform

**Comment by nzjoel1234** [comment]
@jquense I think why this seems strange is that a textbox triggers onChange on every key press.
So it is not so much that onChange should be triggered when pressing enter but rather that onChange should be called after each keypress if the entered text is a valid date.

Would this be possible?

**Comment by jquense** [comment]
It's not feasible given how crazy date parsing is and the nature of pluggable i18n backends unfortunately

**Comment by cleverettgirl** [comment]
Has anyone figured out a solution that has worked for them? I'm using datetimepicker and I'd like to be able to have a warning for when a user manually types/pastes into the input a date that is before min date / after max. I was validating on every keystroke before using widgets. I'd like similar behavior with the widgets.. Thanks in advance!

**Comment by jquense** [comment]
@cleverettgirl the key and onPaste events should work here, you can always manually parse the string value and make a choice about whatever. You can also listen to onChange and validate that the date fits in your range there
