### ISSUE TITLE
Styling list element in Dropdown

### ISSUE THREAD

**Issue by jeron-diovis** [jquense/react-widgets#246]
I am a beginner with this lib. It looked very cool for me... until I tried to style `ul` element in my DropdownList.

I see that `<List>` component is [used](https://github.com/jquense/react-widgets/blob/master/src%2FDropdownList.jsx#L199-L200), and that it, expectedly, [accepts](https://github.com/jquense/react-widgets/blob/master/src%2FList.jsx#L119) a `className` prop. But, `<DropdownList>` itself [does not allow](https://github.com/jquense/react-widgets/blob/master/src%2FDropdownList.jsx#L132) to pass `className` to `<List>`.

Fortunately, it is possible to [create own List component](https://github.com/jquense/react-widgets/blob/master/src%2FDropdownList.jsx#L127). So it should be as easy as this:
```jsx
class MyList extends React.Component {
   render() {
      return <List {...this.props} className="myClass" />;
   }
}
```
A bit verbose as for just adding classname, but looks logical as for common principles of this lib.

But, suddenly, **no**, approach above does not work - because, first, it fails [here](https://github.com/jquense/react-widgets/blob/master/src%2FDropdownList.jsx#L132), requiring to define at least empty `propTypes`, and then it fails at component update stage, because `List` must have certain instance methods, provided by mixins.

After trying several options, finally I ended up with this:
```jsx
import List from "react-widgets/lib/List";
class MyList extends List {
  static defaultProps = Object.assign({}, List.defaultProps, {
    className: "select-btn__list"
  }
}
```
It works. But it's definitely a madness to write all that boilerplate to just add a class.

So I want to ask: is it how things supposed to be? Did I miss something and is there a way to do it easier?

**Comment by jquense** [comment]
hi, yeah the much easier way to do this would be to just use a css selector. and add the class to the dropdown.

```css
.select-btn__list  .rw-list {
 //whatever
}
```

**Comment by jeron-diovis** [comment]
=) Tricky. 
But it creates coupling with concrete library in my styles. Not very good.

Why not to do smth like this:
```
let listProps = pick(this.props, Object.keys(List.propTypes));
listProps.className = this.props.listClassName;
```
?

**Comment by jquense** [comment]
I don't think its tricky, I think its just using css correctly...

I'd rather not add another hook here. It doesn't reduce any complexity or "coupling" to your css the only difference is that instead of your class def being: `.my-class { }` its `.my-class rw-list { }`. The class is already going to be tightly coupled to the library, bc you are styling/resetting a specific list, not just _any_ list. 

I am not trying to support inline/js styles here (or solve any of the issues with css), so the appropriate approach to styling inner elements is to use css, which is exactly what css is for.

**Comment by jeron-diovis** [comment]
Probably same approach you used on demo pages, to hide *everywhere* the `.rw-sr` element with "open dropdown" default message, which definitely nobody needs by default...

Ok, I understood.

**Comment by jquense** [comment]
glad to help. Just any FYI, those messages are __definitely__ needed by default.  Reason the messages are there and _hidden_ is that otherwise vision impaired users would not be able to know what the buttons do. Screen Readers will read the "open dropdown" message out loud, when the button is focused; it is hidden so sighted users don't see them.
