### ISSUE TITLE
Unset date when field is blank (DateTimePicker)

### ISSUE THREAD

**Issue by jjvattamattom** [jquense/react-widgets#251]
I like that DateTimePicker (+moment) tries to pick up correct dates. "19" for 19th of this month, "18 dec" or "18 december" for December 18 of this year and even "abc" as today. Corrupting a string (making it unparsable to the very lenient parser) will revert it to last-known valid date. 

The current version appears to be unable to set date to null when I completely clear the input. When the input has changed to '' (or whitespace), the callback should call (null, ''). Does this feature exist, or could you implement it? 

I was kinda expecting a inputAttributes props to DateTimePicker that is implemented as `<input {...inputAttributes}>` so I could put in a change listener myself.

I use:
react-widgets@3.1.0 node_modules/react-widgets
moment@2.10.6 node_modules/moment

Thank you for the awesome widget. It beats everything else in usability.

**Comment by jquense** [comment]
hi there, I might  not be understanding you, but it does set the value to null when you clear the date. 

and you can listen for change using onChange and value

**Comment by jjvattamattom** [comment]
Strange. I noticed that clearing the field never triggered onChange. Using calendar and clock and even pasting a valid time triggers onChange. Clearing the field and pasting whitespace does not, and removing focus brings the previous value.

My DateTime component uses DateTimePicker as below. It's rendering is controlled by parent component. It imports/exports ISO strings.

```
      <DateTimePicker
        defaultValue={this.props.value? new Date(this.props.value): null}
        onChange={(date,string)=>{console.log(date); this.props.onChange(date.toISOString())}}
        format="DD MMM YYYY HH:mm"
      />
```

**Comment by jquense** [comment]
You can see from the [example](http://jquense.github.io/react-widgets/docs/#/datetimepicker/onChange) here that clearing the value does trigger a change, and does _not_ reset the last good value (I am not sure where you are getting that behavior from). It should be mentioned though that you should always use `null` as your empty value, setting `undefined` will tell the widget that it should track the value internally in state.

The change event doesn't fire until you blur out of the text input when typing, like a normal html input. This is because parsing dates can't be done cha by char, so you need to wait until the user is done typing to try.
