### ISSUE TITLE
For the default twitter bootstrap theme a component should include the `form-control` class

### ISSUE THREAD

**Issue by zerkms** [jquense/react-widgets#253]
Instead of defining paddings and other stuff manually.

Why: it's supposed by twitter bootstrap. Otherwise you cannot guarantee react widgets and other form controls have the same dimensions.

For example: if one uses `form-group-sm` then the react widgets would be bigger than expected and than the other inputs and in fact will not fit the height.

PS: in particular I'm having this issue with `DateTime` picker.

**Comment by jquense** [comment]
Hey there!

the bootstrap theme is just a simple theme, and even then its really just meant to be more of an "ok" default, than an actual theme. To that end I am not adding all the extra input or form-control classes which go above and beyond what the default theme is trying to provide.

There are a few choices I've made with the defaults that differ substantially from the normal bootstrap inputs, like sizing everything using `em`s instead of hard coded pixels, in general this is more flexible for folks not using bootstrap. 

In your case if you do want to control the sizes of the inputs to match bootstrap I suggest changing the `input-height` and `line-height` LESS variables to be a fixed size, like the bootstrap values are. then you can more easily adjust them to suit your needs with helper classes like input-sm or form-group-sm

**Comment by zerkms** [comment]
It's even simpler:

whoever experiences the same problem and wants a cheaper solution - just apply these styles to the `form-controll`ed element:

        padding-top: 0;
        padding-left: 0;

PS: @jquense thanks for the response
