### ISSUE TITLE
Provide an easy way to extend react-widgets to make it work with other data structures

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#259]
Immutable data structures become more and more popular in React community. But one of the biggest issues of using them is that there is no straightforward way to integrate them with third-party components like react-widgets. That's why we end up with converting immutable data to plain js and back.
I suggest to provide several facade-methods for array manipulation, that anyone can easily override to provide support for any data type he wants.
These methods are  isArray, getArrayLength, getArrayItem.

So originally we will have something like this
```javascript
var _ =

  module.exports = {

    isArray(array) {
      return Array.isArray(array)
    },

    getArrayLength(array) {
      return array.length;
    },

    getArrayItem(array, index) {
      return array[index]
   }
}
```

but if we need, for example Immutable.js support, then we can extend react-widgets in the following way
```javascript
import _ from 'react-widgets/lib/util/_';
import Immutable from 'immutable';

_.has = (o, k) => {
  if (!o) return false;
  if (o instanceof Immutable.Record) return o.has(k);
  else return Object.prototype.hasOwnProperty.call(o, k);
};

_.getArrayLength = (array) => {
  return Immutable.List.isList(array) ? array.size : array.length;
};

_.isArray = (array) => Array.isArray(array) || Immutable.List.isList(array);

_.getArrayItem = (array, index) => {
  if (index < 0) return void 0;
  if (Immutable.List.isList(array)) return array.get(index);
  else return array[index];
};
```

and now we can use 
```javascript
import React, { Component } from 'react';
import Immutable from 'immutable';
import {Combobox} from 'react-widgets';

const Item = Immutable.Record({value: '', group: ''});

const data = Immutable.List([
  new Item({value: 'One', group: '< 3'}),
  new Item({value: 'Two', group: '< 3'}),
  new Item({value: 'Three', group: '>= 3'})
]);

export class App extends Component {
  render() {
    return (
      <div>
        <Combobox
          data={data}
          valueField="value"
          textField="value"
          groupBy="group"
        />
      </div>
    );
  }
}
```

I have small [demo](https://github.com/smashercosmo/react-widgets-immutable-demo) of react-widgets and Immutable.js integration (currently only for Combobox).

And here is the [commit](https://github.com/smashercosmo/react-widgets/commit/4531c855a05842e09852458f80f9f1a46b3d793b) that makes this possible.

Would you be interested in such kind of changes? I think it's pretty small change, but the benefit is huge)

**Comment by jquense** [comment]
Hey there, thanks for taking the time to look into this, i appreciate it. 

the problem with supporting none js objects/arrays though is that the level of complexity and maintainence burden starts to skyrocket. 

even from the above example it already requires that I take Immutable as a dependency which adds alot of weight for folks not using it. or I have to do some sort of adapter pattern like the localizers, but they are already a lot to maintain. 

the above example is also a bit misleading in it's simplicity because it doesn't include: map, reduce, every, some, slice, splice, etc. the other thing is that suddenly versions of react widgets are tied to version updates and API breakages of these libraries. ultimately it's not a complexity that I have the time or will to support.

as a slight aside you can already use immutable records/objects without any additional work, since you can provide a function to textField and valueField. just the data props that need to be arrays.

**Comment by smashercosmo** [comment]
> I take Immutable as a dependency which adds alot of weight for folks not using it
mmm... don't get It) Why would you take Immutable as a dependency? I was talking only about providing three facade-methods for array manipulation, which anyone could override.

**Comment by smashercosmo** [comment]
> the above example is also a bit misleading in it's simplicity because it doesn't include: map, reduce, every, some, slice, splice

Again, don't get it) Why do we need them?

**Comment by jquense** [comment]
> Again, don't get it) Why do we need them?

because these are array methods that are used and assumed to be there by all the widgets. I am assuming the reason that you didn't need to provide them is that the ComboBox doesn't use all of them and/or Immutable lists implement some of them already. The point is, the assumption of arrays throughout the library is a lot more extensive than 3 facade methods.

I appreciate that you are trying to propose a way to do this that takes the burden off of me, but practically that's not likely. I need to have a good enough working knowledge of the libraries you would be stubbing, in order to provide a complete and adequate interface to override. I also don't feel comfortable "adding support" for that without proper integration tests. Eventually I hope that es6 iterables will provide the abstraction interface that you want, but at the moment the idea of maintaining something like that myself, is not feasible.
