### ISSUE TITLE
stopPropagation not called after onCreate

### ISSUE THREAD

**Issue by terinjokes** [jquense/react-widgets#262]
I have a Multiselect within a form, and the expectations is that hitting "enter" would create the new tag, but not submit the form. However, `stopPropagation` is never called, so the tag is created, then the form is immediately submitted. The `onCreate` handler is not called with the event, so I can not call it myself.

This is repeatable even with the documented "ctrl-enter" behavior.

**Comment by jquense** [comment]
hey there, thanks for the heads up.

I generally dislike calling stopPropagation since it kills the event...does preventDefault work as expected here? I'd be happy to add that.

**Comment by terinjokes** [comment]
No. The default behavior is already ignored, since another DOM element in
the propagation chain is handling the event.

**Comment by jquense** [comment]
So my tests indicate that calling `preventDefault()` does work for preventing form submission, and I made that change in 3.2.0 

can you test and let me know if that doesn't solve the issue?

**Comment by terinjokes** [comment]
@jquense the form is being submitted JS, not via the default browser behavior.

**Comment by jquense** [comment]
Sorry I am not sure I understand the problem then. If you are manually listening for enter keys and triggering form submission, can you just not listen...or check if the event has its defaultPrevented.

if you want to manually kill the event yourself you should be listening for `onKeyDown` which will give you the event, since you will need to catch it when hitting enter to select from the list as well (not just onCreate).

**Comment by jquense** [comment]
closing due to stallness, let me know if the above is still insufficient!
