### ISSUE TITLE
[Feature request] Option to create new tag on blur event in multiSelect

### ISSUE THREAD

**Issue by gtoma4** [jquense/react-widgets#265]
I am using the multiSelect for either selecting a 'user' from a list or entering a new user's email address.  I have an onCreate callback function that will validate the email address when 'enter' is pressed, however I would also like the onCreate callback to run on blur.

**Comment by jquense** [comment]
I would implement this most likely by just firing the onCreate prop on Blur. You can actually do that yourself by listening for both onCreate and onBlur and running your creation logic in each. Since this is fairly simple to implement (I think) oneself and I don't know that this behavior is super useful more generally I think I will pass in implementing it here.

thanks for the suggestion and taking the time pass it on! Sorry for the delay in getting back to you!
