### ISSUE TITLE
Strange behavior with Number Picker

### ISSUE THREAD

**Issue by yleclanche** [jquense/react-widgets#269]
Hello.

No code exemple here, because this behavior can be seen on the demo page :  http://jquense.github.io/react-widgets/docs/#/numberpicker

To reproduce, just set a float value in the input like "2.5".
Now leave focus, the value is now 2.
Focus the input again, it's 2.5.

I tried on a dev machine and get the same behavior, even when setting an integer format.
The worst things with this, is that the value saved in the field is the decimal value, and not the displayed one.
So when you get the value you get a float value when you expect an integer one.
I find it very confusing.

**Comment by jquense** [comment]
There is a number value that the Picker is bound to and then there is is what is displayed. The issue is that the format you have configured is not displaying the decimals, probably because its configured to show just an integer. You can adjust the `format` to whatever you want to show of the value, depending on which localization option you are using
