### ISSUE TITLE
dropdown aria warnings

### ISSUE THREAD

**Issue by avo** [jquense/react-widgets#270]
These are small issues, but my company is committed to passing accessibility guidelines. It would be great if these could be tweaked. Using two accessibility auditing tools (Chrome extensions: aXe and Accessibility Developer Tools) on a dropdown implementation (screenshots added) the following is occurring:

If filtering is not enabled, than the required ARIA child role of textbox is not present.
The aria attribute aria-readonly="false" is not allowed.

![screen shot 2015-12-16 at 11 40 18 am](https://cloud.githubusercontent.com/assets/477524/11849141/e9bd514a-a3eb-11e5-9097-1e4885ce2946.png)
![screen shot 2015-12-16 at 11 39 32 am](https://cloud.githubusercontent.com/assets/477524/11849140/e9bcf038-a3eb-11e5-94b6-e975fa79c32e.png)
![screen shot 2015-12-16 at 11 39 22 am](https://cloud.githubusercontent.com/assets/477524/11849142/e9c0fb38-a3eb-11e5-9d8a-19789255c937.png)

**Comment by jquense** [comment]
hey there, thanks for the issue, we strive to make sure that each widget is accessible, so reaports like this are helpful. In these cases however, I think your tool is either being too rigid or incorrect.

as I read the spec `false` is a valid value for the `aria-readonly` attribute according to : [this](http://www.w3.org/TR/wai-aria/states_and_properties#aria-readonly). Generally I would jsut opt for removing it if its not present but since this is React I can't actually control that on the component.

To your second issue about a missing `textbox` role, that one is a bit fuzzier. This is a good example where we chose the pragmatic approach to the more "spec-compliant" one. There is nothing that can be given a 'textbox' role in the dropdown, so instead we'd have to choose a different top-level role instead of `combobox`. That option presents problems, since nothing else actually gets close to what the dropdown _is_. The best option is `listbox`, however, screen readers we've testing (Nvda, JAWS) do not read it correctly, with the popup and the selected single value. The readers _do_ however deal with the combobox role quite correctly, despite the missing "required" child role. Also if it helps this is the same approch taken by jQuery UI's [selectmenu](https://jqueryui.com/selectmenu/), which is notable b/c that project is well regarded for its a11y support.

That being said I am open to improvements or tweaks, if you have any suggestions!

**Comment by jquense** [comment]
closing due to staleness

**Comment by matt-potts** [comment]
I know that this has been closed for some time, however, I'm in a similar situation. Screenshot below.

I would suggest removing the aria-readonly attribute entirely unless requested through props since the attribute is false by default, and therefore redundant. 

![Screen Shot 2019-03-20 at 4 35 50 PM](https://user-images.githubusercontent.com/13987889/54717451-901e6280-4b2e-11e9-9965-7488a7bf0e3d.png)
