### ISSUE TITLE
 Don't bring up keyboard when selecting date/time from mobile

### ISSUE THREAD

**Issue by yarsunny** [jquense/react-widgets#272]
In case of Date & Time picker. The mobile keyboard pops up when i try to select a date/time

**Comment by jquense** [comment]
hi there, I don't think there is anything I can do about that, the input has a textbox and you'd need the keyboard to type into it. Plus I don't think I can control when it pops up

**Comment by mkornblum** [comment]
@yarsunny we had a similar issue. Our solution was to use the MediaQuery component from (react-responsive)[https://github.com/contra/react-responsive] to conditionally render the react-widget date & time picker on larger screens while rendering a regular, non-date picker input for mobile screens. It seems to work pretty well for us. Hope this helps!

**Comment by raythree** [comment]
This works perfectly on iOS and Android to prevent the keyboard, but obviously prevents them which I don't see as an issue because they want to use the popup controls anyway:

document.getElementById("rw_1_input").readOnly = true;

However it would be nice to expose somehow the id of the inner input element?
