### ISSUE TITLE
Open the calendar to a different date

### ISSUE THREAD

**Issue by yleclanche** [jquense/react-widgets#294]
Hello, 

I don't find the appropriate props in the documentation, so I'll ask here : 
When you open the calendar, it shows the current month. What if I want to show a different month by default ? Is it possible to open the calendar on another month ?

Thanks.

**Comment by jquense** [comment]
Hi there,

The Calendar will open to whatever the `value` of the Calendar/Datepicker is, when no value it defaults to the current month. Currently though there is no way of adjusting that default.

**Comment by yleclanche** [comment]
Thanks for your answer.

**Comment by slybridges** [comment]
Hi @jquense,

Would you be willing to reopen this issue if I would submit a PR that would allow to open the calendar at a specific date ?

I'm thinking for example of adding a props `defaultDate` to `Calendar` and `DateTimePicker` components that could optionally take a `Date object`. If none are provided, it would revert to the current behaviour using today's date.

Let me know your thoughts, i really would need to have that feature on my project :-)

**Comment by jquense** [comment]
I might be open to it but can you talk to me about what the use case is?

**Comment by slybridges** [comment]
I have a travel form. A travel has many stops, each stop has a departure and arrival date). 
The dates are optional but they must be in a chronological order. 

When the user selects a date, I want the DatePicker to open with the view of the previously selected date in the form (i.e. if i'm editing the arrival of the 3rd stop in the form and no value has been selected yet, I want the default view to show the departure date of the 2nd stop by default).

In my case the dates are optional so I don't want to use `defaultValue` or pre-fill input box, I just want to have the DatePicker open on a specific date so that the user doesn't waste clicks in getting back close to the date he just entered.

**Comment by jquense** [comment]
that seems fair, though I think the correct way to do this is probably: #261 which means pushing the calendar state "currentDate" out to props, then it can take advantage of the uncontrolled bahvior, and have a defaultCurrentDate

**Comment by jquense** [comment]
you can see I've already started to mock out the API here: https://github.com/jquense/react-widgets/blob/master/src/Calendar.jsx#L434 if you want to pick it up and finish it i'd happily merge it
