### ISSUE TITLE
react-intl localizer

### ISSUE THREAD

**Issue by bsr203** [jquense/react-widgets#298]
In the [doc](http://jquense.github.io/react-widgets/docs/#/i18n) there is a section on how to write custom localizer and mentions `Intl`. It would be great to have a builtin support for `react-intl` as it is a popular choice. Do you foresee adding it ?

thanks,
bsr

**Comment by jquense** [comment]
So react-intl runs runs on top of the native Intl (or polyfill) api that some browsers implement. The _general_ problem with that API though is that it doesn't provide any way to _parse_ strings back into numbers or dates.

Adding a localizer that used react-intl directly wouldn't quite make sense since that contains just a bunch of react Components, but using the underlying Intl API would. However At the moment I don't want to support it here because of the parsing concern doesn't let me provide something that would be a solid as I'd like.

**Comment by bsr203** [comment]
thanks Jason for the quick response. It all make sense :-) I will use moment localizer for now. thanks again for the help.
