### ISSUE TITLE
Add property to control button placement without reversing calendar layout.

### ISSUE THREAD

**Issue by jgkingston** [jquense/react-widgets#302]
It would be nice to be able to place the button on the left for consistency with other input component styles.

**Comment by jquense** [comment]
thanks for the suggestion but I am a little bit confused about which part you are talking about, could you clarify?

**Comment by jgkingston** [comment]
Thank you for following up!

We are looking into accessible react data-pickers for a project. To stay consistent with the other form elements we are using it would be ideal if the button with the calendar/clock icons could be displayed on the left as in the screen shot below. Currently however the Right to left prop reverses the whole calendar, presumably for localization:

![screen shot 2016-01-23 at 8 29 21 am](https://cloud.githubusercontent.com/assets/8235431/12530375/7bffaab2-c1ab-11e5-9950-3015ebb37eac.png)

![screen shot 2016-01-23 at 8 29 33 am](https://cloud.githubusercontent.com/assets/8235431/12530374/7bfd8fc0-c1ab-11e5-9106-58e0ee3e4ad3.png)

Additionally and beyond that it would be helpful if the classes used to style this component could be exposed as props so that it can be used in a project that relies on CSS modules that styles components locally by default.

**Comment by jquense** [comment]
thanks for the clarification :) I don't think I'm going to add this sort of thing the API, since it's a design concern which is handled in the stylesheet. In this case you should just adjust or override the default styles to place the select button on whatever side you'd like (just use the right to left style). 

in terms of css modules you can already use set the className for the component. In general the supported approach for theming or styling components is normal css/less. I'm not likely to expose more hooks there since supporting some/all the inline style use cases is to complex
