### ISSUE TITLE
Getting ref inside of componentWillReceiveProps in Combobox.jsx

### ISSUE THREAD

**Issue by ipselon** [jquense/react-widgets#309]
It seems that ref should not be obtained inside of componentWillReceiveProps.

File Combobox.jsx, line 122.
`isSuggesting = this.refs.input.isSuggesting()`

**Comment by jquense** [comment]
why not?

**Comment by ipselon** [comment]
I'm not sure, but I have error: `TypeError: this.refs.input is undefined` on that line every time when Combobox is rendering dynamically (when container component changes his state and Combobox should be rendered).
But there is no such error when page is loaded in the first time.

**Comment by jquense** [comment]
I don't think whatever is going in is related to the library since this works just fine for everyone else...perhaps you have two versions of React installed accidentally.

**Comment by ipselon** [comment]
OK, thanks.

**Comment by idolize** [comment]
I'm having this exact problem - identical error message and everything (came here to file the bug and saw it already exists):

```
Combobox.js:185 Uncaught TypeError: Cannot read property 'isSuggesting' of undefined
```

I'm sure I do not have two versions of React installed. I did, however, just update `react-widgets` from 3.1.3 to 3.1.7, which caused the problem to be introduced. Reverting to 3.1.3 fixes the issue.

**Comment by idolize** [comment]
@jquense Sorry to bother, but any chance of looking at this?

**Comment by jquense** [comment]
I'd be happy to look into it, but I can't repo it. if you can provide more info or something I can reproduce I'll fix it nice and quick

**Comment by idolize** [comment]
I'm definitely still seeing this.

<img width="1050" alt="SCREENSHOT OF ERROR" src="https://cloud.githubusercontent.com/assets/635005/13192513/c49f79b0-d721-11e5-89be-ec19ca1aa4a6.png">

The best I can tell you is that it happens consistently ever time I mount the component in my form. Once the form is up and a new react-router route loads (thus not unmounting the component but simply passing it new props) it does not show the error.


```jsx
export default class TimezoneSelector extends Component {
  static propTypes = {
    timezones: PropTypes.arrayOf(PropTypes.string).isRequired,
    label: PropTypes.node.isRequired,
    help: PropTypes.string,
    placeholder: PropTypes.string,
    value: PropTypes.string,
    onChange: PropTypes.func.isRequired
  };

  static defaultProps = {
    label: 'Timezone',
    placeholder: 'Enter timezone'
  };

  render() {
    const { placeholder, label, value, timezones, help, onChange } = this.props;
    return (
      <Input label={label} help={help}>
        <Combobox
          suggest={true}
          placeholder={placeholder}
          data={timezones}
          value={value}
          onChange={onChange} />
      </Input>
    );
  }
}
```

**Comment by idolize** [comment]
Perhaps an easy fix would be to just change that line to:
```js
isSuggesting = this.refs.input && this.refs.input.isSuggesting()
```

**Comment by jquense** [comment]
that is an easy fix, but the problem here is that there is __zero__ way that the parent combobox could be rendered without the input also being rendered. There is no conditional, or switch that would have one render without the other. 

I don't feel comfortable adding a guard until I can understand what the problem is, and whether its even a bug in the widget. My guess here is still multiple instances of React, or barring that there must be a bug in React, or a race condition where something is unmounting quickly.

**Comment by idolizesc** [comment]
@jquense I'm sure I don't have multiple instances of React - I'm very careful about that (plus I'm sure that would cause other issues).

I hear what you're saying though. If I get time I can definitely go more in depth and try to create the most minimal example I can that reproduces the bug. In the meantime, I do think it would be nice to just put in the guard, even if it's temporary with a comment or something. Otherwise there's not much I can do on in my app to prevent an exception from occurring - since it is definitely occurring inside code for the widget.
