### ISSUE TITLE
Make close icon in multiselect tabbable

### ISSUE THREAD

**Issue by smashercosmo** [jquense/react-widgets#342]
Currently close icon has tabindex=-1, what makes impossible to navigate through tags with keyboard and remove them by pressing enter. What was the reason for that? Seems like it makes component less accessable.

**Comment by jquense** [comment]
Good question, there is a reason for it. Correct tab behavior of an input like these means that hit tab key moves focus to the next input, not within an input. So when the multiselect is tabbed to the whole multiselect should be focused and hitting tab again should move it off the multiselect.

That being said we still need to allow keyboard navigation of the widget so that it can be used without a mouse. Deleting tags can be done by hitting the Backspace key, or you can use the arrow keys (left/right) to select a specific tab and remove it with the delete key.
