### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by amakk** [jquense/react-widgets#45]
Hi, this looks like a great library and exactly what I need for my project. I'm using server side rendering and encountering an error in dom.js line 7: `  , el = document.createElement('div')` because `document` doesn't exist. Has anyone tried using this library with server side rendering or know of a fix/workaround for this? 

Thanks!

**Comment by jquense** [comment]
good Question, 

I am not super familiar with server rendering react components, but I don't think it will work right out of  the box unless you mock out document/window. This is because of the `dom.js` util module expecting the DOM. 

I do think though that just checking for the DOM and returning early in that module will probably be all that is needed to get everything to work, I will look into a bit and see if I can't just hack something together real quick

**Comment by amakk** [comment]
This is awesome, thank you jquense! I was just going to try your suggested workaround but you beat me to it. Cheers!

**Comment by jquense** [comment]
NP let me know if you run into issues, the tests pass but they are very simple so I may be missing something ;)
