### ISSUE TITLE
MultiSelect Doesn't update data and value prop.

### ISSUE THREAD

**Issue by SanjayHarkaj** [jquense/react-widgets#451]
After updating the props of data and value Multiselect still shows the old UI, it doesn't update.
Pls tell me what to do???

**Comment by jquense** [comment]
please provide code demonstrating the issue so I have something to actually work with

**Comment by SanjayHarkaj** [comment]
Code is too big to actually show but i am sharing the screen shots of debugging and ui to show the properties value.
![iteration-1](https://cloud.githubusercontent.com/assets/15974958/18129175/fe0aa8fe-6fa2-11e6-92e7-2c7f13a3fe74.png)
![iteration-2](https://cloud.githubusercontent.com/assets/15974958/18129176/fe0bdd64-6fa2-11e6-9ba4-220abae405ec.png)

**Comment by jquense** [comment]
thanks for the screenshots, however they aren't all that helpful. Seeing the problem doesn't help me identify the issue here. If I recreate your code it works fine. I need the smallest chunk of code that demonstrates the problem, not your whole component. Please take your component and trim it down until it's just the multiselect and the the value setting. If the problem goes away it's likely somethng else. Like the place where the component is rendered not actually updating:

```
let multiselect = <Multiselect value={newValue />

return (
  <PureComponent>
      {multiselect}
  </PureComponent>
)
```

that may not update depending on how PureComponent's shouldComponentUpdate is configured.

**Comment by tonilaukka** [comment]
Are you using default values? My mistake was that I was trying to update defaultValue prop after ComponenWillUpdate received new props. All default values are triggered on first render and after that the component itself takes care of them.
