### ISSUE TITLE
Using React Widgets / Globalize with Create React App

### ISSUE THREAD

**Issue by simon-online** [jquense/react-widgets#486]
There's an issue when trying to use React Widgets / Globalize in an app created with Create React App. It's actually specifically to do with getting Globalize to work in a webpack build environment but I thought I would mention it here first as using React Widgets / Globalize is the recommended set up.

It's basically this issue here but in a Create React App restricted webpack environment:
https://github.com/jquery/globalize/issues/441

Create React App is Facebook's officially supported way to create single-page React applications. It's intended to be a no configuration starting point to get developers up and running quickly with the limitation that if you want to be able to keep your app up to date with the latest version of Create React App you can't eject your app (manually take over managing configuration and dependencies).

As a temporary work around I've modified the webpack config in the Create React App with the work around you've suggested here without ejecting my app from Create React App:
https://github.com/jquery/globalize/issues/441#issuecomment-102859098

However this is not the proper way to use Create React App if you want to keep up to date with newer releases as I'll need to keep making this change to the webpack config every time the Create React App scripts package is updated.

Going forward it would be great if React Widgets / Globalize could work seemlessly with Create React App. However it may require working something out with the Globalize and / or Create React App developers. It would be good if the GlobalizePlugin webpack solution could alternatively have locale config set in the app code instead of the webpack config. However it would still require convincing the Create React App developers to include the GlobalizePlugin into the internal webpack config. Perhaps the best solution is to find a way to get Globalize to work with webpack without any webpack config.

**Comment by jquense** [comment]
Hi i feel your pain. Here is the problem generally, stuff like internationalization just can't be done correctly with "zero configuration", which puts it at odds with something like CRA, even something like like react-intl wants you to add it's babel-plugin to extract messages you define inline. Also you do really want to extract all your format usage and "compile" it ahead of time so your app isn't spend a lot of time just managing and compiling dates.

That said, I totally agree with you that setting up Globalize is much. much. harder and more complicated than it needs to be. [This setup](https://github.com/jquense/react-widgets/blob/v4/.storybook/configure-globalize-new.js) is the simplest i've been able to come across and shouldn't require any build step **except** for that fact that their UMD module format just doesn't work well with webpack, so [this line](https://github.com/jquense/react-widgets/blob/v4/build/webpack.config.js#L53) is required to ignore the AMD module stuff. I still consider this a bug on Globalizes part, and I think it'd be super helpful to present your use-case to them so that folks using CRA can still make use of globalize, even if its not in the specific way they want you too.

**Comment by simon-online** [comment]
Yes, good point Globalize probably isn't the best option when using CRA.

Using the Moment and Simple Number localizers is probably fine for what I need.

**Comment by metaclass-nl** [comment]
Or you could try https://github.com/timarney/react-app-rewired, it allows you to override create-react-app configurations without ejecting.

If you want an example with globalize.js working out of the box you could try https://github.com/metaclass-nl/switch-language-example-globalize, it does not use create-react-app but its usage should be likewise. Furthermore it lets the user change the locale without reloading the app, and loads precompiled formatters and parsers dynamically.

**Comment by simon-online** [comment]
Nice. Thanks for the suggestion @metaclass-nl
