### ISSUE TITLE
Missing unique "key" prop in iterator for options

### ISSUE THREAD

**Issue by joshreid** [jquense/react-widgets#516]
Using the DropdownList or other widget with multiple options...

Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of '[component]'. See https://fb.me/react-warning-keys for more information.

Looks like we just need to add the key prop into render loop?

**Comment by jquense** [comment]
hi there, what version are you using?

**Comment by joshreid** [comment]
3.4.5 - sorry, so update to latest should fix this warning?

**Comment by jquense** [comment]
I don't think the warning is comingfrom react-widgets. I'm fairly certain I would have seen it myself at this point if it did. You have any more info?

**Comment by joshreid** [comment]
I'll look into it further and let you know - thanks for your prompt responses @jquense

**Comment by joshreid** [comment]
Apologies - We've tracked it to another component, BTW thanks for building such an excellent resource!

**Comment by jquense** [comment]
glad you enjoy it!

**Comment by Gaetanbrl** [comment]
Hi,

I get the same error.
Think it's due to same "key" for many combo.

Here, 2 combobox.
![image](https://user-images.githubusercontent.com/16317988/111188993-eb687b80-85b5-11eb-8e98-b8776da38c30.png)


They have same `<li>` keys if we control with react components inspector :

![image](https://user-images.githubusercontent.com/16317988/111189415-56b24d80-85b6-11eb-8e02-e9fb1c430380.png)

SO, i think this is warning source : 

```
react.development.js:175 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Tabou2SearchPanel`. See https://fb.me/react-warning-keys for more information.
    in Tabou2Combo (created by Tabou2SearchPanel)
```

Where "Tabou2Combo" is react-widget combo.

Could we create prefix for combo keys ?
