### ISSUE TITLE
Suggestion: clearable prop to display an 'x' button to clear the value

### ISSUE THREAD

**Issue by kromit** [jquense/react-widgets#584]
The user can clear the `Multiselect` by removing each item from it, but the `DropdownList` can not be cleared from inside of the component. Also removing more that 5 items one by one from `Multiselect` is ineffective. A default clear button `x` at the and of the input is a common UI element so it would be great to have an option for it.

`<DropdownList defaultValue={"orange"} data={colors} clearable/>`

**Comment by jquense** [comment]
I would like to make this possible for both the MS and dropdownlist, but i haven't been particularly satisfied with the UX of examples i've seen, are there any examples you've seen that do a good job at this UX?

**Comment by waynebrantley** [comment]
http://select2.github.io/select2/#multi
The dropdown under 'placeholders' for picking a state

**Comment by jole78** [comment]
I just wanted to leave a comment here to explain i technique I've been using to accomplish a "clear" button with the Dropdown.
I've used the 'valueComponent' prop that you can supply to the Dropdown and have that render both the value and a button/span/whatever that is absolutely positioned to the far right. I made a HOC that takes an onClick handler to handle the 'onClear' button click event etc...it looks something like this.

You need a custom 'wrapper' around the Dropdown to track the value and the onChange event within the Dropdown itself. The render function looks something like this:

```
        return (
            <DropdownList
                {...this.props}
                value={this.state.value}
                onChange={this.onSelectionChange}
                valueComponent={WithClearableSelection(this.onSelectionClear)}
            />

....
function WithClearableSelection(onClear ) {
    return ({ item }) => (
        <React.Fragment>
            <span>{item.someprop}</span>
            <ClearSelectionButton onClick={onClear}>x</ClearSelectionButton>
        </React.Fragment>
    );
}
```
This gist of this is that you need to supply an event handler to the custom value component factory function and have that return you a component that takes the item (the selected item) and render it. If you need more control (or generalization) you can supply more parameters to the HOC function (for example how it should put together its value when rendering etc).

The actual 'clear' button could be anything really. Since I'm using styled-components here's my version of it just as an example:

```
const ClearSelectionButton = styled("span").attrs({
    title: "clear selection",
    "aria-label": "clear selection",
})`
    color: #999;
    cursor: pointer;
    margin-left: auto;
    position: absolute;
    right: 0;

    &:hover {
        color: #d0021b;
    }
`;
```

Hope this at least helps someone...

**Comment by flyfishMT** [comment]
Hello I was wondering if this was ever implemented? This would be a very nice feature.
