### ISSUE TITLE
Multiselect input overflow

### ISSUE THREAD

**Issue by ojame** [jquense/react-widgets#59]
![image](https://cloud.githubusercontent.com/assets/2898239/6588034/5254c88e-c7e0-11e4-9638-7eefcb31aa4c.png)

This is because `rw-input` is a text input, which doesn't allow multiple lines. Having a `textarea` instead might be a decent solution, in combination with something like [autosize](https://github.com/andreypopp/react-textarea-autosize) which would allow a single line, but grow if the tag becomes too long for the parent.

What are your thoughts on this?

**Comment by jquense** [comment]
My immediate thought is just to stick a `max-width: 100%` style on the input and let it scroll. I am not at all sure whether all browsers would treat that the way i'd expect though... I think the textarea is probably a more complete solution, but I would be worried about the added complexity compared to what you get for it. Especially since, reasonably tags that long seem unusual.

in slightly related news, I also need to fix the overflow behavior on the dropdown as well...

**Comment by ojame** [comment]
`2.3.0` really fixed this for me in a cleaner way. The combination of maximum tag length and then a maximum width on the input worked a treat. We also have a decent ellipsis tag overflow too.
