### ISSUE TITLE
Add pagination to Combobox component

### ISSUE THREAD

**Issue by MV88** [jquense/react-widgets#591]
Hello people!
This is a feature request. 

What I need is a toolbar containing the pagination positioned below the options list.
I also need to not close the list if the pagination is clicked (at the moment the handleSelect method always close the options list)

Could you introduce this new feature in a new component let's say ComboboxPaginated?
Or do you know if there are other libraries that manage combobox list and pagination?

Thanks ahead of time. 
MV

**Comment by jquense** [comment]
Hi there, I don't think i'm gonna spend time writing such a version of the ComboBox since its a pretty unique UX that isn't common. You can, however, implement this over the current API. The `List` component is changeable and you can use that to change it out and control specific behavior there. I would take a look at how the `virtualized` versions of RW are implemented in the v4 branch as a starting point.

**Comment by MV88** [comment]
Hi @jquense i have a question related to this issue.
i added a special option to the option list which is the toolbar of the pagination and it is working properly.
There is this line which https://github.com/jquense/react-widgets/blob/master/lib/Combobox.js#L382 closes the combobox when i click on the pagination tools. Is there a way to avoid this behaviour only for some particular options?

Even if i customize the List component i will not avoid this behaviour or am i wrong?

Thanks,
MV
