### ISSUE TITLE
[v4] rc.16 Multiselect continues selecting instead of submitting on [ENTER]

### ISSUE THREAD

**Issue by jasonrobinson** [jquense/react-widgets#616]
First, fantastic job on this library. Very well done.

I have been using v4 rc.10 as a baseline for considering upgrading to new v4 rc's, and I recently tried v4 rc.16. 

My recollection of v3 may be rusty, but v4 rc.10 submits on [ENTER], with selections made by mouse or touch. In contrast, v4 rc.16 selects every item in the list sequentially on holding down [ENTER], without submitting the form. 

Is that expected? Or am I missing something?

**Comment by jquense** [comment]
That depends. The behavior for when the list closes for multiselect has changed. Previously it would close on selection, either via the mouse or keyboard. In v4 it stays open when you select, which makes it easier to select multiple options faster. 

The behavior your seeing of containing to select while the button is pressed is wrong, but probably caused by listening to keydown and the menu staying up. This doesn't happen when the menu is closed right?

**Comment by jasonrobinson** [comment]
Correct -- if the menu is closed, then there is no exhaustive addition on enter, and the form submits normally (e.g. using submit, DatePicker, etc.).

**Comment by jasonrobinson** [comment]
Minor correction -- I use v4 rc.10 for a baseline (I use v4 rc.6 as a baseline for react-widgets-moment). I'll update the comment above for correctness.

**Comment by jasonrobinson** [comment]
Just tried 4.0.1, which has the same behavior. Is this a "Closed-Won't Fix"?

**Comment by jasonrobinson** [comment]
I got around this by maintaining open state and toggling open in onSelect/onToggle. Thank you.
