### ISSUE TITLE
Multiselect ARIA

### ISSUE THREAD

**Issue by Filip0** [jquense/react-widgets#620]
Hi,
I have been trying to solve some problems I'm having with Multiselect being read correctly in JAWS.
One of the problems is active elements, v4 sets the ```aria-activedescendant``` attribute to the static value ```n_listbox_active_option``` and changes the id of the active element. I'm no expert in ARIA coding but this seems like an issue with screenreaders. When the ```aria-activedescendant``` never changes how does it know which element is selected?

**Comment by jquense** [comment]
Hey there, In most SR's it notices when the id moves to a new element and announces it, from the test's i've  done anyway. This is also how a few other libraries work in terms of moving focus. It's otherwise very hard to give each item a separate id, since the parent component (e.g. the one controlling activedescendant) doesn't know what they are.
