### ISSUE TITLE
Number picker backspace bug

### ISSUE THREAD

**Issue by tmcw** [jquense/react-widgets#63]
Had to test this because we've run into it so many times in our own code :)

If you type 15.55 in a number picker:

![2015-03-13 at 9 02 am](https://cloud.githubusercontent.com/assets/32314/6638766/a514b52c-c95f-11e4-93d4-903adbd6979d.png)

And then hit backspace, when you hit backspace on `15.5`, it'll pop from `15.` to `15`. This is because the parseInt of `15.` _is_ `15`, and so it replaces the input.

My solution to this so far is to confirm that both string and numeric representations of the input are different before allowing the component to update, but there may be a cleverer solution.

**Comment by jquense** [comment]
Ya this is an annoying issue. I am not sure how to fix it without having some sort of knowledge of what the decimal point char is for a culture, which I want to avoid.

I may just be misreading it, but i don't think your workaround will work in this particular case.

we have `1.5` (number: `1.5`, string: `'1.5'`) -> `1.` (number: `1`, string: `'1.'`) In either case the last values don't give us anything to compare to. I can't make compare that the string/numbers === because it doesn't cover cases where there are thousands place marks ( `"1,000"` vs `1000`).

I manage to avoid this when typing in a number because I can compare that the number values are different. Any suggestions are much appreciated :)
