### ISSUE TITLE
MultiSelect performance with ~6000 records

### ISSUE THREAD

**Issue by aleemb** [jquense/react-widgets#636]
I have a dropdown with approximately 6000 records and when using the MultiSelect widget, the performance is severely degraded. Clicking within the MultiSelect results in a 4-5 second lag before the dropdown appears. Removing an item also takes 4-5 seconds.

Any tips for now or perf tweaks in a future release would be awesome.

**Comment by jquense** [comment]
Yes perf for that many items is gonna be bad because frankly browsers and React suck at rendering large lists. The general strategy for avoiding this is to use windowing or virtual lists, where you only render the visible items. React-widgets v4 has a companion addon react-widgets-virtualized that integrates this into the components.

**Comment by aleemb** [comment]
A few further questions. I have noticed there is an excessive delay in even deleting an item that is already selected, even if I have just 2 selected items and I am deleting one of them.

Would it make sense to make virtual rendering the default? The drop down only shows like 10 or so items at any given time the rest are not visible in any case. Maybe something along the lines of keeping the dropdown items in an array and then on filter, only render those items. This would mean the dropdown doesn't render at all unless the user types in a character and the filter finds the top 10 matches on those. A settings flag for this sort of behaviour would help for large lists with the caveat that the dropdown would only render a filtered list after a user types a character.

**Comment by jquense** [comment]
It doesn't generally make sense to make virtualizing the default because < 20 items is most common. In addition there are always tradeoffs to that strategy, not to mention a lot of extra code to make it work.

I think your thoughts on how to optimize for your use case sound great, and I'm certain the API to implement it as a wrapper is already there. In the general case tho it's hard to pick something that works for lots of use cases

**Comment by aleemb** [comment]
@jquense am going with virtualized approach, which works really well. Thanks a bunch!
