### ISSUE TITLE
Can not get Combobox name property value in onChange function 

### ISSUE THREAD

**Issue by shic** [jquense/react-widgets#715]
I read in react-widgets documentation :
```
name
type: string
The HTML name attribute, passed directly to the input element.

```
And I what to get the name property value in Combobox onChange function . So I wrote:

```
<Combobox
                data={featuredWeightList}
                valueField="id"
                textField="displayName"
                name="featuredWeight"
                defaultValue={featuredWeight}
                value={featuredWeight}
                onChange={this.handleFeaturedWeightChange}
              />

  handleFeaturedWeightChange = (evt) => {
    const id = evt.id;
    const id = evt.displayName;
    // I do not have name property in evt variable 

  };
```
I do not have name property in evt variable, I got only "id" and "displayName" property.

But a normal html input, I can get directly name property in onChange function. Like this:
```
            <Input
              type="text"
              name="address"
              value={door.address}
              onChange={this.handleInputChange}
            />

  handleInputChange = (evt) => {
    const target = evt.target;
    const name = target.name;
    console.log('Input value: ', value);
    console.log('Input name: ', name);
  };
```

 I Want to get the component name in onChange function so I can use the same handler to handle different components.

So does someone have some suggestion about **How to get Combobox name property value in onChange function ?**

Thanks!

**Comment by jquense** [comment]
The first argument in onChange is the value object not the event. The second argument is probably the event but these are custom inputs so the target isn't going to be the underlying input element all the time, I'd suggest using a closure or similar to pass the name to the handler. Thanks!

**Comment by shic** [comment]
@jquense In fact I checked the second argument, it does not contain name. 

If we can not get name value, why do we have name property in Combobox? We use it in other occasions? 

I tried different ways to pass parameter :
1. 
```
function handleFeaturedWeightChange(event){
  console.log(event.target.dataset.id);
}

<Combobox
    data-id={id}
    onChange={this.handleFeaturedWeightChange('1234')}
/>
```
Not works because event.target does not contain dataset

2.
```

<Combobox
    data-id={id}
    onChange={this.handleFeaturedWeightChange('world')}
/>

  handleFeaturedWeightChange = (data, evt, param2) => {
    const { onChangeDoor, door } = this.props;

    console.log(data, evt, param2);
    // Output: "world", undefined, undefined 
  };
```

Not works because I lost all other data passed

3.
```
 <Combobox
        onChange={(param) => this.handleFeaturedWeightChange(param,'world')}
 />

  handleFeaturedWeightChange = (data, param) => {
    console.log(data, param);
  }
```
This Works.

Hope this is useful for who has the same problem.

**Comment by jquense** [comment]
Name is for the html input, so that it's properly annotated, for the html's sake.  it's really not for storing some state to retrieve in the handler (in general you don't want to do that in React, store it in your component). Your example with the closure and arrow function is how I'd do it.

**Comment by shic** [comment]
@jquense Thanks a lot for the help!

**Comment by joshlongerbeam** [comment]
@jquense 

> it's really not for storing some state to retrieve in the handler (...you don't want to do that in React...

According to the React docs on [handling multiple inputs](https://reactjs.org/docs/forms.html#handling-multiple-inputs) that's exactly what the `name` prop is recommended for.

```
 <Combobox
        onChange={(param) => this.handleFeaturedWeightChange(param,'world')}
 />
```
Using an arrow function within the prop-assignment (as above) is not recommended because it creates a new function every single time the containing `render` function is called, which leads to false-positives for shadow-DOM-diffing and unnecessary DOM repaints.

As much as I'd like to see the `event` be given to the handlers, I agree that it could get confusing if the actual target of the event is inconsistent. But given that the `name` prop is an explicitly-set attribute, I would hope to see it come back in the handlers.

**Comment by jquense** [comment]
> Using an arrow function within the prop-assignment (as above) is not recommended 

Not sure if you've seen the new React Hooks api, but the entire api is built around declaring functions in render. The prohibition to declaring function in render is something that developed outside of official react recommendations, out of an misguided sense of what the performance issue was. new functions can defeat shouldComponentUpdate, but you can handle that via memoizing or using an instance method on a class. otherwise there isn't really any performance concern with passing a new function in every time

**Comment by joshlongerbeam** [comment]
Heard about React Hooks, but didn't know what they were. I'll look into them.

> misguided sense of what the performance issue was
That premature-optimization bit sounds very familiar, too.

Fair points. And thanks for the speedy response.
