### ISSUE TITLE
Date disappears if invalid when exiting DateTimePicker

### ISSUE THREAD

**Issue by waynebrantley** [jquense/react-widgets#725]
Using DateTimePicker, if you key in a date that does NOT match the format of the control and tab out of the control it simply erases what you typed.

It would be better to maybe style it as invalid and leave what they typed in the box.

You can see this by going here
http://jquense.github.io/react-widgets/api/DateTimePicker/
And choosing last format type "MMM-dd-yy" ...then key in 12-15-2017 and press tab.

**Comment by jquense** [comment]
the date disappears because it ends up being parsed as `null` yeah. The UX for this is tough, if you leave the bad date its not clear to the user that something is wrong or how to fix it even if you do style the input as invalid (input could be invalid for lots of reasons). I agree tho that the current behavior can also be confusing. I'm open to proposals for a better way

**Comment by waynebrantley** [comment]
To start with, I think the input should be made to be invalid with a style or whatever.
I guess you could make it optionally clear that input to be backwards compatible.
As far as 'why' it is invalid - that is complex, but the control should at least handle 'invalid date'. 

So, I am thinking start with something simple like adding a style when it is an invalid date and not clearing it?

**Comment by BarthesSimpson** [comment]
My opinion is that any string value should be allowed, and leave the validation logic up to the user.

**Comment by waynebrantley** [comment]
@BarthesSimpson That is valid, perhaps there should be a handler for validating the date.  It could default to the date actually matching the format you gave...but you could provide a different one to do what you want.  It returns true/false..

**Comment by jquense** [comment]
Its not validating the date, it's parsing it from the input string. The point of the input is to select `Date` values not strings. It's significantly less useful if the value of the input was just a string, you could use a plain textbox for that. The parsing logic is completely configurable so if anyone is unhappy with how and when it fails it's straightforward to customize it to ones liking :)

**Comment by waynebrantley** [comment]
It would be nice if it showed what it though was invalid though.
I was thinking for @BarthesSimpson, might want to take the word 'today' or something and he could allow that.  But sounds like you  have it covered.

Can we just leave the bad value in the input - and add a class to the input when it is invalid or something  - as it is - its very confusing to users.

**Comment by BarthesSimpson** [comment]
@jquense "The point of the input is to select Date values not strings."

Some users prefer to type in dates as strings. Most other datepickers out there allow this.

**Comment by jquense** [comment]
I think you may have misunderstood, the point is the value is parsed as a date, of course you can type in a date as a string, but it's turned into a date object. Almost no date pickers just pass through the typed string, again that just a textbox

**Comment by BarthesSimpson** [comment]
@jquense Actually, pretty much every other datepicker that allows the user to type in the input does exactly that. For instance, [react-datepicker](https://reactdatepicker.com/), [react-bootstrap-datepicker](http://pushtell.github.io/react-bootstrap-date-picker/), [react-datetime](https://codepen.io/arqex/pen/BNRNBw). Even old school [jQuery datepicker](https://jqueryui.com/datepicker/). 

The point is that users prefer to type in dates, and they may type malformed dates. How to handle those malformed dates should be up to the developer. Your datepicker component is too opinionated in coercing the value of the input to null when the date entered is unparseable. It's a good component otherwise, but that decision makes it unusable for many business cases.

**Comment by jquense** [comment]
As i've said leaving the typed string in the input is terrible UX, the user believes they have entered a valid value but its _actually_ null. I have explicitly decided against that simple default in part because of users who were constantly confused as to why their data was wrong despite looking fine. I've also noted here that i'm happy to improve the UX of the existing component, but not by picking a different bad default.

> How to handle those malformed dates should be up to the developer

Like i've noted above this is already the case. you have complete control over what value is parsed and how. In addition the `onChange` event always fires with the string value as well as the Date value

**Comment by waynebrantley** [comment]
I think we are simply asking to allow the bad value to stay in the box - but the style of the box change (add a class)...and not erase what is there.

**Comment by BarthesSimpson** [comment]
@jquense "As i've said leaving the typed string in the input is terrible UX" - as the library author, it's your prerogative to implement the component however you wish, but you are in the minority in holding this opinion.

The issue is here in lines 102-109 of [DateTimePickerInput](https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/DateTimePickerInput.js): 

```
function formatDate(date, format, culture){
  var val = ''"
  if ( (date instanceof Date) && isValid(date) )
    val = dateLocalizer.format(date, format, culture)

  return val;
}
```
It would make more sense, IMO, to start with `var val = date` (or if you are concerned about sanitizing input, add an `else if (typeof date === 'string') { val = date }`). Then it's up to the developer to validate whether the input is acceptable. For instance, there are plenty of use cases where a (malformed) typed-in date would be perfectly acceptable, but a datepicker is also provided for convenience.

I decided to use a different library, and I'm going to leave this thread, but I'd encourage you to rethink this one because the UX you've chosen is very idiosyncratic, and makes your otherwise very nice component unusable for many legitimate cases.

**Comment by jquense** [comment]
If anyway is interested in changing this I happily accept PRs. As is the current behavior works well enough for my users and improving it is not high on my priority list. I would warn anyone tho that it is likely a non trivial change! But definitely encourage anyone unhappy with the behavior to jump in, I'm more than happy to offer code base insight in a PR. Thanks!

**Comment by waynebrantley** [comment]
@BarthesSimpson Curious, what did you switch to?

**Comment by BarthesSimpson** [comment]
@waynebrantley I went with [react-datepicker](https://reactdatepicker.com/)

**Comment by jwhitex** [comment]
@jquense I propose this change. (which I can PR)

If the date argument is a valid date according to runtime then the call to construct a Date object will return a Date, otherwise NaN. 

If a valid date is passed to this function then it will return that argument formatted.

```
function formatDate(date, format, culture){
  var val = new Date(date)
  if ( isNaN(val) )
    return ''
  if ( (date instanceof Date) && isValid(date) )
    val = dateLocalizer.format(date, format, culture)
  else
    val = dateLocalizer.format(val, format, culture)
  return val;
}
```

If you will accept, I will open.

**Comment by waynebrantley** [comment]
> The parsing logic is completely configurable so if anyone is unhappy with how and when it fails it's straightforward to customize it to ones liking :)

I do not see where we would be able to customize the formatDate function.  I agree that the ``dateLocalizer.format`` is customizable, but by the time that is called the value is already erased.  Perhaps a way to override the formatDate would help with the above. 

As far as turning the control red if invalid or whatever, perhaps there could be another function ``IsValid()`` that is customizable by the end user.  If that returns false, you add some type of error-class to the component, if it is true you remove it.  You could let the user pass in the class name - or you could just pick one and with css we could override.

**Comment by toddcoulson** [comment]
It should be noted I switched to http://projects.wojtekmaj.pl/react-datetime-picker/ because this component did not offer a way to type in a date, even though an input field is included. Poor design out of the box.
