### ISSUE TITLE
Create keywords on paste/blur

### ISSUE THREAD

**Issue by MJfenix** [jquense/react-widgets#737]
First of all, let me say that your widgets are really cool. 

I have a requirement where users want the keywords to be created on pasting or on blur from the widget.

I went through the documentation and since it does not have onBlur option, I gave it one by passing it to the inputProps. But how do I call the 'onCreate' from the onBlur. As per my understanding 'name' is only available for 'onCreate' ?

Any help would be appreciated :)

**Comment by jquense** [comment]
All inputs supports onBlur but aren't explicitly documented since they are native html events (but we should document them).

onPaste can work via `inputProps` but you'll need to handle the "create" part yourself. There is nothing magically about how tags are created, if you want to do it "manually", onPaste add a new item to your `data`, and `value` and it'll just work
