### ISSUE TITLE
Typescript to inherit from or contain the widgets

### ISSUE THREAD

**Issue by tremmorkeep** [jquense/react-widgets#776]
Our solution requires that we wrap inputs into our security components (to lock/unlock and override) if a user can use/see the input.  I've tried all kinds of ways and I just end up with an error.  Ideally I'd be something like:
`import Calendar = require("widgets/calendar")
export class SecureCalendar extends React.Component<any, any>{
let calendar = Calendar;
if(!securityCheck())
  calendar.enabled = false;
   render()  {return <div id="decorated-with-security-crap"><Calendar props..../></div>);
}`

it should be stated that our solution is in .NET studio, no node, webpack, etc etc etc etc.

**Comment by jquense** [comment]
I'm not sure sure how to to do that, I don't often use typescript. I'd assume tho the logic is the same as for any react component

**Comment by tremmorkeep** [comment]
yes, the code above throws (typically) mismatched define() errors

**Comment by tremmorkeep** [comment]
I know you have this licensed under MIT, would it give you heartburn if I port it all to TS?

**Comment by jquense** [comment]
You mean fork and port it to typescript? Your welcome to do whatever of course, but I'm not sure why you wouldn't just write type defs instead. I'm still not sure what your even asking for here the code example above if very hard to read. But any typescript specific errors are due to bad configuration on your end not a problem with the library
