### ISSUE TITLE
Time only issue - couple of issues

### ISSUE THREAD

**Issue by akatreyt** [jquense/react-widgets#78]
I'm using DateTimePicker with calendar = false because I'm only interested in the time components. There two issues I'm facing:

when choosing a time I still get full dateTime instead of just the time. I fixed this by doing 
```
var d1 = new Date(time);
        var minute = d1.getMinutes();
        if(minute.len === 1)
        {
            minute = minute + "0"
        }
        var hour = d1.getHours();
        var newOpenTime = hour+":"+minute;
```
a real huge hack but gets the job done.

second issue is the data that I get back,  from the sever,  to edit looks like 07:00:00 or 23:00:00, mysql TIME. I set this as the value of the dateTimerPicker when editing an object, but since the DateTimePicker needs a full date time this fails.

Are there any elegant solutions to the two issues above?

Thanks

**Comment by jquense** [comment]
Unfortunately there isn't really an elegant solution, your dealing with type interop issues between MySql and Javascript. Since Javascript doesn't have just a Time type you need to parse the time string from the server into a date object which is the closest thing we have (and you can't have empty date parts). This is going to be the same for you regardless of the picker you use.

If you don't want to deal with parsing directly you can use a date parsing solution like Globalize (used by react-widgets) or Moment.js (another really popular one) to more easily parse a string to a date, and dates to the string format you want. 

You can even wrap the widget to handle this for you if you always want to input a string and get back a string.

```js
class MyTimePicker extends React.Component {

  render(){
    // convert the passed in string to a date object
    var value = globalize.parseDate(this.props.value, 'HH:mm:ss')
    // convert it back to a string in the right format on the way out
    var changeHandler = date => this.props.onChange(globalize.format(date,  'HH:mm:ss')

    return <DateTimePicker {...this.props} time={false} value={value} onChange={changeHandler}/>
  }
}

MyTimePicker.propTypes = {
  value: React.PropTypes.string,
  onChange: React.PropTypes.func
}
```
