### ISSUE TITLE
Unsure how to handle ERR_INVALID_URL error

### ISSUE THREAD

**Issue by sietekk** [jquense/react-widgets#81]
Hello jquense,

We are working on bundling react-widgets with Webpack and Bower with our software stack, and we are running into this ERR_INVALID_URL error (posted with traceback in screenshot below):

![screen shot 2015-04-08 at 10 06 42 am](https://cloud.githubusercontent.com/assets/11478589/7073520/00a67ab6-dec2-11e4-9b8d-d98445511655.png)

After shoehorning the unminified code into our bundling process, I've discovered that if the "?v=4.1.0" substring is removed, then the error disappears. I removed that string from the react-widgets.css file in the dist/css directory here (lines 58-59):
```
src: url('../fonts/rw-widgets.eot?v=4.1.0');
src: url('../fonts/rw-widgets.eot?#iefix&v=4.1.0') format('embedded-opentype'), url('../fonts/rw-widgets.woff?v=4.1.0') format('woff'), url('../fonts/rw-widgets.ttf?v=4.1.0') format('truetype'), url('../fonts/rw-widgets.svg?v=4.1.0#fontawesomeregular') format('svg');
```

which becomes

```
src: url('../fonts/rw-widgets.eot');
src: url('../fonts/rw-widgets.eot?#iefix') format('embedded-opentype'), url('../fonts/rw-widgets.woff') format('woff'), url('../fonts/rw-widgets.ttf') format('truetype'), url('../fonts/rw-widgets.svg#fontawesomeregular') format('svg');
```

So, we aren't sure how to handle this issue. I found a related issue [here](https://github.com/webpack/url-loader/issues/7).

Thanks,
Mike

**Comment by jquense** [comment]
I believe this is a problem with your webpack setup (or version of webpack you are using), since the plain css file works fine when just included as `<link/>` resource.

If you are using webpack to include css then I would recommend requiring the less file directly from `react-widgets/lib/less`. Otherwise, I am not sure how to fix it, maybe make sure you are using a build of webpack that has that issue you linked merged in. In either case I don't think its related to react-widgets specifically.
