### ISSUE TITLE
Multiselect doesn't create the typed name

### ISSUE THREAD

**Issue by texels** [jquense/react-widgets#831]
Going to the demo page for Multiselect and typing 'aaa' into the first example field and pressing return should result in in 'aaa' being added, but it looks like maybe the focused list element gets added instead.

![image](https://user-images.githubusercontent.com/24467307/43739479-349548f6-9996-11e8-8d51-758322baa018.png)

result:
![image](https://user-images.githubusercontent.com/24467307/43740021-096dc5fc-9998-11e8-937b-6755eb979503.png)

**Comment by mowsmith** [comment]
Any information on this? I think I might have a related problem. 

My data array is dynamically generated and when I fill out the value to get only one match, and I select it with `enter`, I don't get that one remaining value. It seems like it remains focused on the first value it matched when the data array was created. 

It's for zips, so typing `40241` selects `40003` even though it's not in the data array anymore. 
The same happens when typing `402` and hitting `enter` which has multiple matches.

It seems to not be focusing on the top element of the dropdown. 

Hitting down to select the first item and then hitting enter works just fine, but not everyone is doing that in the app.

**Comment by jquense** [comment]
Definitely a bug!
