### ISSUE TITLE
Allow accessor functions as valueField

### ISSUE THREAD

**Issue by pigulla** [jquense/react-widgets#84]
I'm trying to use the DropdownList widget with [Immutable](https://github.com/facebook/immutable-js). The problem is that there are no properties on immutable objects, only accessor functions. This means that `textField` and `valueField` are problematic.

The `textField` prop can be avoided by using a `valueComponent`. However, I don't see a way to avoid the `valueField`. So as it stands I need to convert my immutable list via `toJS` in order to use it as the `data` prop (which can cause performance issues).

This could be solved by allowing custom accessor functions like so:

```js
<DropdownList
    value={this.prop.someImmutableValue}
    data={this.prop.someImmutableList}
    valueGetter={value => value.get('id')}
    textGetter={value => value.get('name')}
/>
```

With `value` and `valueGetter` as well as `textField` and `textGetter` being mutually exclusive.

**Comment by jquense** [comment]
I have been thinking about doing this, I haven't had the time recently though, as a change like this needs a lot of testing, given how fundamental the value/text getters are to widget assumptions. I will probably implement the function signature for textField really soon though, which brings me to the next point.

One possible way around it is that you could use a [`Record`](http://facebook.github.io/immutable-js/docs/#/Record) as the value type, as the get/sets work as expected on that type (since the properties are known in advance)

Even without the Record, you may not need to worry about the `valueField`. The widgets are designed to take advantage of immutability if you can provide it. In other words you can just use reference identity as the "value field", provided the the `data` prop is array like enough (`length`, and es5 iteration methods like `forEach`, `filter`, etc). The valueField is really an escape hatch for when you only have an the value of the valueField (such as an `id`).

```jsx
<DropdownList
    value={this.prop.someImmutableValue} // { id: 12, name: 'John' }
    data={this.prop.someImmutableList}
    textGetter={value => value.get('name')} // still need this  unless you use a record :/
/>
```
Without the `valueField` the dropdown it will just use `indexOf` and `===` equality checks with are going to be a lot faster than finding a record with a specific id field.

**Comment by pigulla** [comment]
Thanks for the info, seems like the need for accessors isn't all that urgent then :)

However, Immutable apparently isn't too fond of the widget using the `length` property:

```js
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version
```

**Comment by jquense** [comment]
Yeah, I probably need to look into just accepting any iterable for `data`, but we are bit to far from that language-wise, right now. I am keeping it in mind though.

As a middle ground `toArray()` for the list will still be pretty cheap compared to `toJS()` and since the widgets don't care at all about the contents of the list really that should work just fine.

**Comment by pigulla** [comment]
Allright, thank you!

**Comment by grovesNL** [comment]
@jquense How hard do you think it would it be to add this functionality at this point? I would be happy to attempt a PR if you don't expect it to be too bad.

FYI for my use case I'm using TypeScript, so I'm trying to avoid using strings everywhere for this type of property access (I lose type safety when properties are renamed etc.). `valueField={item => item.id}` would be great, because the type of `item` could be inferred

**Comment by jquense** [comment]
already added in v4!

**Comment by grovesNL** [comment]
@jquense Sounds great! Looking forward to it.

**Comment by jquense** [comment]
can use it now if you want `npm i react-widgets@next` its pretty stable.
