### ISSUE TITLE
dropdownlist defaultValue not working

### ISSUE THREAD

**Issue by jangtrektang** [jquense/react-widgets#848]
Hey guys,

I'm having a issue with your dropdownlist. It wont take the defaultValue i select.
I'm using typescript. Here is my code
![image](https://user-images.githubusercontent.com/24461077/45864120-3c96ac00-bd79-11e8-95f3-ab9f8d1094ec.png)

and this is how it looks: 
![image](https://user-images.githubusercontent.com/24461077/45864146-52a46c80-bd79-11e8-8152-d92128c659a8.png)
![image](https://user-images.githubusercontent.com/24461077/45864156-5a641100-bd79-11e8-8f5b-4212a2050ad9.png)

so as you can see my data array is filled and they show up perfectly in the dropdown, but it just wont take the first one as the default value.

Any idea how to solve this?

**Comment by heyjaypray** [comment]
I'm also having this issue

`  <DropdownList {...input}
    data={data}
    valueField={valueField}
    textField={textField}
    onChange={input.onChange}
    defaultValue={data[0]}
    />`

**Comment by kkerley** [comment]
Also having this issue but with a multiselect using Redux Form.

**Comment by benf35** [comment]
Hello, I had this issue with a textArea too.

The defaultValue can only be set the first time with a value.

In my case, I was doing an API call to fill the Textara, and so during this time, the render() method was called with defaultValue set to undefined. After that, I could'nt fill it again with my new values.

To prevent this strange behavior, I added some code around my Textarea to wait my defaultValue to be loaded before rendering my component.

Here the example, I want to have a list of files set as a default value  : 

```
render() {
      [...]
        return (
                [...]
                { this.state && this.state.selectedFiles &&            
                  <Multiselect
                    data={this.state.files}
                    defaultValue={this.state.selectedFiles}
                 />
                [...]
                }
          )
}
```
Hope it will solve your problem, but don't really know if yes, without knowing where your value field is coming.

**Comment by kkerley** [comment]
@benf35 thanks for your response! I ultimately ended up with a similar solution by checking for the value in the passed-in props to the form from the form page it lives on. In the event the API call hadn't finished and the global state was still missing the value I needed, I output a "loading" div. 

The other issue was my fault: I was sending an object to the defaultValue, not an array with a single object in it. 

The issue I'm encountering now is with a multiselect. There are a bunch of staff members and the first with user_type: "SURGEON" needs to be default selected. So, using what I realized above, I got that default value to appear. However, for some reason, unless I add another staff member to that field, Redux Form fails to recognize the fact there is an option selected and the form fails to submit because at least one staff member must be chosen. 

So there's a default value being successfully passed in, yet Redux Form won't recognize it upon submission.

**Comment by alyssa1995** [comment]
still having this issue with my code and it's not working. Still no solution?

**Comment by jquense** [comment]
I'll take a took ya'll.

**Comment by nurhanna** [comment]
yeah, I'm also facing the same issue with MultiSelect "defaultValue", I can set the "value" accordingly based on the same data, but not for "defaultValue",it won't display as it should. Any workaround on this? Thanks!
