### ISSUE TITLE
Open time picker once date is chosen on the Date Time Picker

### ISSUE THREAD

**Issue by ryanMeredith** [jquense/react-widgets#854]
Feature request or advice on how to wrap the component.

When picking a date it automatically sets the time as current time and closes the date picker. Would it be possible to close the date picker and auto open the time picker when you pick a date?

Thanks for any help. Thanks for your work on these, they are amazingly good.

**Comment by jquense** [comment]
glad you like em. You can control the `onToggle` and `open` props in coordination with the onSelect event to achieve what you want I think. Listen for onSelect, and when the date is set, set a flag noting it in your wrapper, when the onToggle event fires, instead of syncing the `false` value, sync `time` instead
