### ISSUE TITLE
DropdownList  not going outside of bounding containers

### ISSUE THREAD

**Issue by prathamesh-bhandare-invimatic** [jquense/react-widgets#871]
It seems that dropdownList seem to render only within the parent container that the select is in, instead of being on top of the entire page.
On a parent div we have style={{overflow: "auto"}} as we need scrollbars on the smaller screen sizes. In this scenario the dropdownList gets cut off when we open it. It remains inside the div.

Is there any solution for this problem? I tried googling a lot but could not find a solution. I found a solution for react-select but not one which works for react-widget/dropdownList

**Comment by jquense** [comment]
There are a couple previous issues on this but yeah, that's a known limitation. absolutely positioning the overlay as a lot of positives in reduced complexity, focus mgmt, and many other edge cases. We may revisit this in v5, because modern React portals solves a few of these issues but it's still a trade off to include a lot of extra positioning logic via Popper.js of similar so it's not set

**Comment by navotaras** [comment]
Greatly appreciate it. Kindly let us know if there is a tentative time line for the fix.  we ask because we are facing some challenges in integrating react-widgets with bulma.css.  This would be of immense value to us and help us with our go live.

**Comment by jquense** [comment]
there is no tentative timeline, I don't consider the current behavior a bug, and it's unclear if we would "fix" it. Beyond that I have no timeline for doing a full v5 release since most of the work on it is in my spare time!

**Comment by pranay-lonkar-invimatic** [comment]
+1
This is a very important issue and is very similar to the following
https://github.com/JedWatson/react-select/issues/810
