### ISSUE TITLE
DateTimePicker Fails to Format when Using Parse

### ISSUE THREAD

**Issue by aedryan** [jquense/react-widgets#935]
When a `parse` prop is provided, the `DateTimePicker` does not format the date on blur when a date that matches the current value and passes the parser is entered.

To reproduce:
- Open [the parse prop example](http://jquense.github.io/react-widgets/api/DateTimePicker/#parse).
- Enter a date in the current year into **the first** example field and tab out.  e.g.: for 2019, "May 14 2019"
- Then enter the 2 digits of current value's the day of the month into the field and tab out.  e.g.: "14".

You will see that it continues to display just the 2 digit day of the month.

![datepicker-parse-problem](https://user-images.githubusercontent.com/11503410/57706351-2d77ad80-762b-11e9-8eba-2f213a6676f3.gif)

**Comment by jmschae** [comment]
I'm experiencing this as well. It seems to be an issue in the DateTimePickerInput's getDerivedStateFromProps function here:

```
let textValue = formatDate(
  value,
  editing && editFormat ? editFormat : format,
  culture
)
if (prevState.lastValueFromProps !== textValue)
return {
  textValue,
  lastValueFromProps: textValue,
}
```

this code takes the value received from props, formats it, and compares it to the formatted string from the previous props.
This does not take into account that the current textValue in state may not match either formatted string. So because both values map to the same string, the input doesn't update.

Something like this would fix this:

```
let textValue = formatDate(
  value,
  editing && editFormat ? editFormat : format,
  culture
)
if (prevState.lastValueFromProps !== textValue) {
  return {
    textValue,
    lastValueFromProps: textValue,
  }
} else if (textValue !== prevState.textValue) {
  return {
    textValue
  }
}
```

My only concern is whether or not this behavior is unpredictable if the value prop updates but the formatted string is the same, and the user is somehow in the middle of typing. This would cause the user's text to be wiped out and the new (but same as previous) text to be put in. I think this puts more onus on the programmer, but ultimately solves more problems than it causes.

I'm also open to any suggestions on better solutions, I'm just trying to start a dialogue.
