### ISSUE TITLE
Keep height consistent when scrolling through months

### ISSUE THREAD

**Issue by mathias-ebx** [jquense/react-widgets#956]
Hi, whenever I scroll through between months rapidly the height of the widget collapses

![Untitled-1](https://user-images.githubusercontent.com/29147584/62621010-0b848300-b91b-11e9-8664-7a65b26ed401.jpg)

**Comment by jquense** [comment]
yeah this is a frustrating bug that is due to react and css transitions being kinda of terrible together. I think we fixed it in v5, but also fairly dramatically changed the look and feel

**Comment by mathias-ebx** [comment]
ok ok - is there an ETA for v5?

**Comment by Dudewonder** [comment]
Is there a way to disable the transitions via CSS or some prop while we wait for v5? The transitions aren't necessary (for me).

**Comment by jquense** [comment]
@Dudewonder you can find the CSS class and set transition: none or similar to disable

**Comment by Dudewonder** [comment]
@jquense I ended up trying that. Setting transition to none, transition-duration to 0s (also tried 1ms) and transform to none. Unfortunately it's not working. There is something timed that is happening regardless as far as I can see from inspecting the html and seeing the classes being added/removed. From looking briefly at the code, I think it's maybe in SlideTransition where it's getting the transition time from the CSS or defaulting to 300ms which seems roughly the same the delay I'm seeing. From what I'm getting from inspecting the html, you're creating a new calendar (dates section) and sliding it in (via CSS) after a delay and the removing the old calendar or overwriting it, right? Do you know how that delay is calculated or can be overwritten (if possible without changing the code)? Because it seems to me if you click fast enough, the app isn't able to queue a calendar for transition fast enough and that's why it goes 'blank' for a bit. I usually can't get more than 3 clicks in (maybe it's capped at queueing 2-3 calendars). Anyway, I'm open to ideas. I'll run a custom version if I have to, I'd just appreciate some direction.
