### ISSUE TITLE
Dropdownlist with filter in redux-form has value set to filter if option is not selected

### ISSUE THREAD

**Issue by Sylv0** [jquense/react-widgets#957]
I'm using the DropdownList within a redux-form and noticed that with a filter the input value is set to the filter string if an option is not selected. This includes an empty filter causing an empty string as input value. This doesn't trigger onChange or any similar functions that I can tell. The behavior I expect in this situation is the previous value to remain selected.

[Example](https://codesandbox.io/embed/react-widgets-redux-form-issue-1k36d) on Codesandbox with similar setup as the project.

**Comment by jquense** [comment]
Looks like the problem is that the `onBlur` event is picking up the nested filter input because of event bubbling. It does seems like a bug on RW's end but i don't think i've ever seen this happen before with other form libraries so unsure why it's not working specifically with redux-form (we use dropdowns in forms a lot!) 

As a workaround i'd suggest not passing onBlur to the dropdown, it's not needed since the value only change via the onChange event

**Comment by Sylv0** [comment]
I just tested and it seems to be working. Thank you for looking into it. Case closed.
